### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by mnovinger** [census-instrumentation/opencensus-js-core#8]
Hi, looks like you're building out this library with the intent leveraging it in both the web and node clients? Just wondering if there's any timeline or road map and whether there's anything you need help with. We're examining using either jaeger but would prefer to build out with open census and then export to jaeger. Neither have a browser client library so we're looking at trying to help one or the other.

**Comment by ofrobots** [comment]
Hi @mnovinger! We are just about getting started, but e haven't progressed enough to have a roadmap or actionable things to do. We would :heart: to have contributions, though! Give us some time to figure things out, and check back in a bit?

**Comment by dragoscirjan** [comment]
Hi! Any progress on this project?

**Comment by atrauzzi** [comment]
Just chiming in to mention that I'm super curious about this as well.  Would love to get a 10,000ft perspective on what kind of relationships in-browser/web-client tracing could have with opencensus.

Obviously lots of distributed and architectural concerns to discuss.  Environments, local logging, where to ship traces from browsers.

Perhaps this project can outline some high level objectives in its wiki to give everyone something to think about?

**Comment by aabmass** [comment]
@ofrobots is there any code released from this repo? I am now maintaining the existing OC JS, just want to know if this repo needs to maintenance or is "dead"

**Comment by ofrobots** [comment]
I haven't paid much attention for a while in this direction, but it seems to be "dead" as far as I can tell. @kjin as FYI too.
